version: 0.2

env:
  variables:
    BUILD_DIR: "dist"

phases:
  build:
    commands:
      - node --version
      - npm --version
      - npm run build
  post_build:
    commands:
      - echo "Syncing to S3 s3://$BUCKET_NAME"
      - aws s3 sync "$BUILD_DIR"/ "s3://$BUCKET_NAME" --delete
      - echo "Creating CloudFront invalidation"
      - aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: $BUILD_DIR
